#!/bin/bash

xrandr --output LVDS --mode 640x480
xrandr --output VGA-0 --mode 640x480 --same-as LVDS
wine pong_windows_app/pong.exe -opengl=1 -fullscreen=0
xrandr --output LVDS --auto
xrandr --output VGA-0 --off
